### ISSUE TITLE
[Suggestion] could you add a select decorator into the helper inspired from ng2-redux

### ISSUE THREAD

**Issue by alyahmedaly** [ngrx/core#10]
I then add a select decorator will be useful when selecting from the store, please find the [discussion](https://www.linkedin.com/groups/8434339/8434339-6183908056527556610?trk=hb_ntf_COMMENTED_ON_GROUP_DISCUSSION_YOU_COMMENTED_ON#commentID_6184022340758683648)

**Comment by SethDavenport** [comment]
@alyahmedaly I put this together as an experiment a little while ago: https://github.com/SethDavenport/ng2-redux-select

Works with ngrx and ng2-redux. However it's pretty experimental at this point. Notably we have some AoT-related fun to resolve. If there's interest we can look to productize it more.
