### ISSUE TITLE
rxjs peer dependency warning with rc.7

### ISSUE THREAD

**Issue by kylecordes** [ngrx/core#7]
The shiny new A2 rc.7 uses rxjs beta 12. The ngrx/core dependency `"rxjs": "5.0.0-beta.11"` produces an NPM warning.

An application here using rc.7 with current ngrx/store and /core appears to work fine, so this may need only the addition of a ^ in the package.json. But I did not run any test suites etc. to see if that is the case... hence this issue instead of a PR.

**Comment by brandonroberts** [comment]
Issue has been resolved
